
---
version: 1

formatters:
  simple: 
    format: '%(asctime)s - %(name)s - %(levelname)s - %(funcName)s:%(lineno)d - %(message)s'

handlers:
  filehandler: 
    formatter: simple
    class: logging.FileHandler
    level: DEBUG
    filename: backlog.log

  console:
    formatter: simple
    class: logging.StreamHandler
    level: INFO
    stream: ext://sys.stdout

loggers:
  main: 
    level: DEBUG
    handlers: [console,filehandler]
    propagate: no

  clustering: 
    level: DEBUG
    handlers: [console,filehandler]
    propagate: no

  dataenrichment:
    level: DEBUG
    handlers: [console,filehandler]
    propagate: no
root:
  level: DEBUG 
  handlers: [filehandler,console]


